### ISSUE TITLE
Can't add new epub file

### ISSUE THREAD

**Issue by delfino-nunez** [BasioMeusPuga/Lector#4]
```
Database returned no paths for settings...
Available parsers: *.epub *.mobi *.azw *.azw3 *.azw4 *.prc *.cbz *.cbr
Database returned nothing
Exception in thread Thread-1:
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/delfino/python/Lector/sorter.py", line 165, in read_book
    book_ref.read_book()
  File "/home/delfino/python/Lector/parsers/epub.py", line 37, in read_book
    contents_found = self.book_ref.read_epub()
  File "/home/delfino/python/Lector/ePub/read_epub.py", line 38, in read_epub
    None, True)
  File "/home/delfino/python/Lector/ePub/read_epub.py", line 74, in get_file_path
    xml = self.parse_xml(container_location, 'xml')
  File "/home/delfino/python/Lector/ePub/read_epub.py", line 63, in parse_xml
    root = BeautifulSoup(this_xml, parser)
  File "/home/delfino/.local/share/virtualenvs/Lector-qOw1XMLY/lib/python3.6/site-packages/bs4/__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/delfino/python/Lector/sorter.py", line 253, in pool_creator
    self.read_book, self.file_list)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?

Finished processing in 0.01865553855895996
Saving settings...
```

**Comment by delfino-nunez** [comment]
I had to install also lxml but still doesn't add any epub to the library.

```
Database returned no paths for settings...
Available parsers: *.epub *.mobi *.azw *.azw3 *.azw4 *.prc *.cbz *.cbr
Finished processing in 0.12314081192016602
Finished processing in 0.12201285362243652
Finished processing in 0.12334322929382324
Finished processing in 0.12205934524536133
Saving settings...
```

**Comment by BasioMeusPuga** [comment]
Could you please link me to that epub? Since they're so easily created, they sometimes don't have uniform structure / conform to standards.

It'll let me know for certain if there's something wrong with the code.

**Comment by vendforce** [comment]
So basically its hit and miss ? not very good .. whats the point in this ..
I've download mutiple epub books and only 1 worked .. 

would you not encorported to rebuild the ebook or try to fix the format if it does'nt meet your stringent requirements

**Comment by BasioMeusPuga** [comment]
@vendforce
The fuck are you on about? All software has a development process and time. Add to the fact that I'm doing this for free. Consider yourself blocked.

**Comment by jojurgens** [comment]
When adding this book:  https://www.gutenberg.org/ebooks/1342 (the *no images* version), nothing appeared in the gui. I restarted, it still wasn't there. 

Then I ran Settings > Scan library. It started scanning 3000 books, so i just restarted. But then the book I'd initially added finally did show up in the gui, and adding new books now works.

Some books work, but I can't open the Gutenberg book. When i double click it, i get...

    Available parsers: *.epub *.mobi *.azw *.azw3 *.azw4 *.prc *.cbz *.cbr
    Attempting to open: C:/Downloads/pg1342.epub
    Exception in thread Thread-1:
    multiprocessing.pool.RemoteTraceback: 
    """
    Traceback (most recent call last):
      File "C:\Pythons\Python3\lib\multiprocessing\pool.py", line 119, in worker
        result = (True, func(*args, **kwds))
      File "C:\Pythons\Python3\lib\multiprocessing\pool.py", line 44, in mapstar
        return list(map(*args))
      File "C:\Pythons\Lector\lector\sorter.py", line 209, in read_book
        all_content = book_ref.get_contents()
      File "C:\Pythons\Lector\parsers\epub.py", line 65, in get_contents
        self.book_ref.parse_chapters(temp_dir=self.temp_dir)
      File "C:\Pythons\Lector\ePub\read_epub.py", line 239, in parse_chapters
        cover_temp.write(self.book['cover'])
    TypeError: a bytes-like object is required, not 'NoneType'
    """
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "C:\Pythons\Python3\lib\threading.py", line 916, in _bootstrap_inner
        self.run()
      File "C:\Pythons\Python3\lib\threading.py", line 864, in run
        self._target(*self._args, **self._kwargs)
      File "C:\Pythons\Lector\lector\sorter.py", line 253, in pool_creator
        self.read_book, self.file_list)
      File "C:\Pythons\Python3\lib\multiprocessing\pool.py", line 266, in map
        return self._map_async(func, iterable, mapstar, chunksize).get()
      File "C:\Pythons\Python3\lib\multiprocessing\pool.py", line 644, in get
        raise self._value
    TypeError: a bytes-like object is required, not 'NoneType'

This is on Windows with Anaconda 3.6.2/PyQt 5.6.0

**Comment by BasioMeusPuga** [comment]
@jojurgens 
It was an oversight on my end considering all the books I'd added had at least one image in them. That book is working now. It's chapters aren't split properly, but I'll fix that soon.

For future reference, please create a new issue even if there's a book that doesn't work. I'd like to be able to tell the reasons apart.

**Comment by delfino-nunez** [comment]
@BasioMeusPuga I tried the following epub https://www.gutenberg.org/ebooks/345  images/no images.

Still doesn't show anything. I did a rebase, I'll try to do a clean clone later.

~/p/Lector> python ./lector/__main__.py
Database returned no paths for settings...
Available parsers: *.epub *.mobi *.azw *.azw3 *.azw4 *.prc *.cbz *.cbr
Saving settings...

**Comment by BasioMeusPuga** [comment]
@delfino-nunez 
That book is working for me. A clean clone would be a good idea, yes. In case it still doesn't function, make sure your installations of Lector's requirements are up to date. Please also furnish details of your platform.

**Comment by delfino-nunez** [comment]
@BasioMeusPuga I did a new clone, but the issue wasn't that.
The issue was that I didn't "scan" the library, after scanning the library it show up some files, but then I found other bugs.
You can see what is happening in the next gif: https://imgur.com/a/rKx4X
If you want I can open other bugs.

Platform:
Linux Neon 5.12 
KDE Plasma 5.12.3
QT 5.10.0
Kernel 4.13.0.36-generic
Python 3.6.3

**Comment by BasioMeusPuga** [comment]
@delfino-nunez 
I've pushed some fixes. Please see if you can replicate those errors.

**Comment by delfino-nunez** [comment]
@BasioMeusPuga I just pulled the latest changes and you introduced a new bug :)

(Lector-qOw1XMLY)  ~/p/Lector> python ./lector/__main__.py
Traceback (most recent call last):
  File "./lector/__main__.py", line 31, in <module>
    from lector.guifunctions import QImageFactory
ModuleNotFoundError: No module named 'lector.guifunctions'
(Lector-qOw1XMLY) ~/p/Lector> git pull
Already up-to-date.
(Lector-qOw1XMLY) delfino@delfino-pc ~/p/Lector> ls -lrt ./lector/guifunctions.py
-rw-rw-r-- 1 delfino delfino 1116 Mar 14 21:31 ./lector/guifunctions.py
(Lector-qOw1XMLY)  ~/p/Lector> grep "QImageFactory" ./lector/guifunctions.py
class QImageFactory:

**Comment by BasioMeusPuga** [comment]
@delfino-nunez 

I've made some additions that will allow launching with `__main__.py`. I've also shaken my fist at the sky and muttered unintelligible cuss words to no one in particular.

**Comment by delfino-nunez** [comment]
@BasioMeusPuga I wonder if I'm doing something wrong my self, just pulled latest changes but still get the same error:

```

delfino@delfino-pc ~/p/Lector> git pull
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 7 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (7/7), done.
From https://github.com/BasioMeusPuga/Lector
   5d3ce17..55545f6  master     -> origin/master
Updating 5d3ce17..55545f6
Fast-forward
 README.md          | 10 ++++++++++
 lector/__main__.py |  8 ++++++++
 2 files changed, 18 insertions(+)

(Lector-qOw1XMLY) delfino@delfino-pc ~/p/Lector> python ./lector/__main__.py
Traceback (most recent call last):
  File "./lector/__main__.py", line 39, in <module>
    from lector.guifunctions import QImageFactory
ModuleNotFoundError: No module named 'lector.guifunctions'
(Lector-qOw1XMLY) delfino@delfino-pc ~/p/Lector> git pull
Already up-to-date.
(Lector-qOw1XMLY) delfino@delfino-pc ~/p/Lector> python ./lector/__main__.py
Traceback (most recent call last):
  File "./lector/__main__.py", line 39, in <module>
    from lector.guifunctions import QImageFactory
ModuleNotFoundError: No module named 'lector.guifunctions'

```
I'll check again tomorrow...

**Comment by BasioMeusPuga** [comment]
@delfino-nunez 

I'm a little confused myself. When you try next, could you just install it instead with the instructions in the README? I would actually recommend that.

**Comment by delfino-nunez** [comment]
Is working now. I did a clean clone and make sure I was using python 3.6 in my virtual environment.
 I found 2 other bugs, but I will create new ones.

I'll close this one.

Thanks
